### PR TITLE
add maartz as contributor

### PR DESCRIPTION
**Pull request by Maartz**

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
Hey @Maartz, thank you for sending this.
We need commits to be signed, including the CLA commit.

Try [Krypton](https://krypt.co/docs/start/code-signing.html) its easier than setting up GPG.

Thank you 🙏

**Comment by Maartz** [comment]
Thanks for your patience ;)

**Comment by mrinalwadhwa** [comment]
Of course, it's great to have you contribute.

Looks like the new commit it signed, but we have some things to solve:
1. the commit is not rebased to the main branch
2. there are two commits in this branch, one signed and one unsigned - you'll have to squash this into one signed commit.
3. github shows the signed commit as unverified, you may need to add your commit email and public key to github.
Screen Shot 2021-04-13 at 10 33 22 PM

Let me know if you need my help with the steps.

**Comment by Maartz** [comment]
Sure thing.
I've tackled the verification of the signature.
Tell me whenever you're free to tackle the two others ;)

**Comment by mrinalwadhwa** [comment]
@Maartz sorry that I missed your request for help with this.
If you still want to, I'd be happy to help. Closing this PR for now since it's now very old. Please open another one when you're ready. Thank you.

**Pull request closed without merging**
