### PR TITLE
docs: added my details

### PR DESCRIPTION
**Pull request by rishabh99-rc**
@mrinalwadhwa, I have added my details in the contributors.csv file & have gone through the CLA as well.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
Hi @rishabh99-rc thank you for accepting the CLA.
We require all commits to be signed.

Here's a good guide from Github on signing commits
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

Please go through it and sign the commits and let me know if you have questions along the way.

**Comment by rishabh99-rc** [comment]
> Hi @rishabh99-rc thank you for accepting the CLA. We require all commits to be signed.
> 
> Here's a good guide from Github on signing commits https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
> 
> Please go through it and sign the commits and let me know if you have questions along the way.

@mrinalwadhwa, I have added the GPG key to my GitHub account, but I am **not able to sign my previous commit**. Since for me, it's showing that:
Screenshot 2021-12-23 at 1 20 38 AM

I have tried using: 
1. git commit --amend -S
2. git commit --amend --signoff

None of this has worked for me, Is there any command, with which I can amend & sign my commit simultaneously ??

**Comment by mrinalwadhwa** [comment]
Do this:

```
git reset HEAD~1
git commit
```

Since you started the PR, a new commit was merged into [main](https://github.com/ockam-network/contributors/commits/main). So you'll also need to rebase to the new main.

Once you've done that.

```
git push --force
```

Let me know if you get stuck in the process.

**Comment by rishabh99-rc** [comment]
> Do this:
> 
> ```
> git reset HEAD~1
> git commit
> ```
> 
> Since you started the PR, a new commit was merged into [main](https://github.com/ockam-network/contributors/commits/main). So you'll also need to rebase to the new main.
> 
> Once you've done that.
> 
> ```
> git push --force
> ```
> 
> Let me know if you get stuck in the process.

yeah, even I thought of the same, in fact I had used **git reset HEAD~1** previously, but the thing is, even after that when I am committing my changes, it is showing: 
_error: gpg failed to sign the data_
_fatal: failed to write commit object_

Screenshot 2021-12-23 at 1 50 52 AM

**Comment by mrinalwadhwa** [comment]
Maybe something is wrong with you gpg config, this post has good set of tests
https://stackoverflow.com/a/41054093

**Comment by mrinalwadhwa** [comment]
If that doesn't work. https://krypt.co/docs/start/code-signing.html this a good tools to make gpg signing a littler easier.

**Comment by rishabh99-rc** [comment]
> Maybe something is wrong with your gpg config, this post has good set of tests
> https://stackoverflow.com/a/41054093

Yeah, even I think so, anyways, let me try it using Krypton. 

hopefully, it should be fine with that.

**Comment by rishabh99-rc** [comment]
@mrinalwadhwa please see, if the issue has been resolved or not. I have signed the commit. 

All thanks to [Nirajan Maharajan]. (https://gist.github.com/paolocarrasco/18ca8fe6e63490ae1be23e84a7039374#gistcomment-3767413)

**Comment by rishabh99-rc** [comment]
@mrinalwadhwa, sorry for the delay, actually I have been slightly busy cause of the Year-end celebrations. 

but finally, [Krypt](https://krypt.co/docs/start/code-signing.html), made things easier & I have signed my commit.

Please do add me to the contributor's list.

**Comment by mrinalwadhwa** [comment]
@rishabh99-rc Happy new year and great work learning how to sign the commits!

Since this PR has a merge commit and commits that are unsigned. We'll need to do a little bit of work to fix that.

https://github.com/ockam-network/contributors/pull/60/commits
Screen Shot 2022-01-01 at 10 33 51 AM

Try this:
1. Make sure you have the latest main branch with `git log`
2. Checkout this PR's branch
3. `git rebase main`
4. git will tell you that there was a conflict in CONTRIBUTORS.csv while rebasing and pause the rebase.
5. Edit CONTRIBUTORS.csv to remove the conflict guards that look like this `>>>>>` and `<<<<<` and make sure that it has all the lines from current main and one additional line that adds your details.
6. `git add CONTRIBUTORS.csv`
7. `git rebase --continue`
8. The conflict error will happen atleast twice, repeat steps 4 to 7.
9. The end result will be a single signed commit in addition to the commits in main branch that adds only a single line with your details.
10. Now we can force push this to the PR - `git push --force`

But before you do, there is one more thing - your commits don't have an authors email. Let's change that:

```
$ git config --global user.name "Rishabh Chauhan"
$ git config --global user.email "binareshu96@gmail.com"
```

11. `git commit --amend` This will fix the author name and email in the commit.
12. `git push --force`

Let me know if you get stuck along the way.

**Comment by mrinalwadhwa** [comment]
While you try the above, this is a good guide to read
https://www.freecodecamp.org/news/the-ultimate-guide-to-git-merge-and-git-rebase/

**Comment by rishabh99-rc** [comment]
> @rishabh99-rc Happy new year and great work learning how to sign the commits!
> 
> Since this PR has a merge commit and commits that are unsigned. We'll need to do a little bit of work to fix that.
> 
> https://github.com/ockam-network/contributors/pull/60/commits Screen Shot 2022-01-01 at 10 33 51 AM
> 
> Try this:
> 
> 1. Make sure you have the latest main branch with `git log`
> 2. Checkout this PR's branch
> 3. `git rebase main`
> 4. git will tell you that there was a conflict in CONTRIBUTORS.csv while rebasing and pause the rebase.
> 5. Edit CONTRIBUTORS.csv to remove the conflict guards that look like this `>>>>>` and `<<<<<` and make sure that it has all the lines from current main and one additional line that adds your details.
> 6. `git add CONTRIBUTORS.csv`
> 7. `git rebase --continue`
> 8. The conflict error will happen atleast twice, repeat steps 4 to 7.
> 9. The end result will be a single signed commit in addition to the commits in main branch that adds only a single line with your details.
> 10. Now we can force push this to the PR - `git push --force`
> 
> But before you do, there is one more thing - your commits don't have an authors email. Let's change that:
> 
> ```
> $ git config --global user.name "Rishabh Chauhan"
> $ git config --global user.email "binareshu96@gmail.com"
> ```
> 
>  11. `git commit --amend` This will fix the author name and email in the commit.
> 12. `git push --force`
> 
> Let me know if you get stuck along the way.

Thanks a lot, @mrinalwadhwa & Happy New Year to you too ..!! 
Hope you'll have a great year ahead. 

Yeah sure, I'll do it today & in case I get stuck somewhere, I'll let you know.

**Comment by rishabh99-rc** [comment]
@mrinalwadhwa I have made the required changes, now I request you to kindly merge this PR. 

thanks in advance & sorry for the delay.

**Comment by mrinalwadhwa** [comment]
@rishabh99-rc since this PR has merge commits, we can't merge the change into the main branch. We only add a rebased linear history to the main branch. If you want to try again, please try with a new PR that might be simpler. I'm closing this PR.

**Pull request closed without merging**
