### PR TITLE
Added name to contributors list

### PR DESCRIPTION
**Pull request by RajivTS**
Added name to contributors list

### CODE REVIEW

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
Thank you for accepting the CLA!

**Comment by mrinalwadhwa** [comment]
@RajivTS we require all commits to be Verifier before merging. Could you sign the commit in this PR please

**Comment by RajivTS** [comment]
@mrinalwadhwa I pushed a new squashed commit that is signed but somehow merging is still blocked. Do you have any ideas?

```
rajshar-mbp:ockam-contributors rajshar$ git log --show-signature
commit e4bc6515ce28fae6c6746ada8e8faa967c1107e1 (HEAD -> rajsha/contributors, origin/rajsha/contributors)
Author: Rajiv Sharma <rajshar@fb.com>
Date:   Sun Sep 4 23:27:02 2022 +0100

    Added name to contributors list
```

**Comment by mrinalwadhwa** [comment]
@RajivTS for me, the commit doesn't look like its signed:

Here's a good test

```
» git verify-commit HEAD && echo "signed" || echo "unsigned"
unsigned
```

An easy fix may be to edit [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) in the Github web ui. This will satisfy our "Verified by Github" requirement.

**Pull request closed without merging**
