### PR TITLE
CONTRIBUTORS.csv - add myself

### PR DESCRIPTION
**Pull request by elpiel**
I don't see how I should add a company but I've added myself to the list.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@elpiel thank you for accepting the CLA, could you do a quick rebase on the branch please so your signature on the commit is maintained when I merge.

**Comment by mrinalwadhwa** [comment]
Also, no need to add a company if you're contributing as an indivisual.

**Comment by elpiel** [comment]
I've rebased, but I would like to add Lechev.space Ltd as a company contributor in a subsequent PR

**Comment by mrinalwadhwa** [comment]
Great, thank you for the rebase, merging this.
I'll send you an email about the company CLA.

**Comment by mrinalwadhwa** [comment]
@elpiel You should have a docusign with the company CLA in your email. Once you sign that I will add Lechev.space to the contributors file.

**Comment by elpiel** [comment]
Signed today. Thanks for reminding it was on my to-do list 😁

**Pull request merged**
