### PR TITLE
Update CONTRIBUTORS.csv

### PR DESCRIPTION
**Pull request by Salonikansal2**

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@Salonikansal2 ah found it. Sorry about the confusion, we are transitioning the contributor list to https://github.com/build-trust/ockam repo.

Did you run into outdated instructions somewhere?

Could you please follow the below instructions:

> Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.
> 
> The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

**Comment by Salonikansal2** [comment]
but its showing my commit in the commit section (just at right of conversation tab)
please check

**Comment by mrinalwadhwa** [comment]
It is but this is not the right repository. The discussion we're having is `ockam-contributors` (this is old and we are retiring it) repository but we need you pull request in the `Ockam` repository

**Comment by Salonikansal2** [comment]
Done, please check.

**Comment by mrinalwadhwa** [comment]
Thank you, that one looks great.
Closing this.

**Pull request closed without merging**
