### PR TITLE
Update CONTRIBUTORS.csv

### PR DESCRIPTION
**Pull request by NathanTarbert**

### CODE REVIEW

**Comment by NathanTarbert** [comment]
CONTRIBUTORS.csv has been updated

**Comment by mrinalwadhwa** [comment]
@NathanTarbert sorry for the slow response, I was traveling this weekend. Would you mind doing a rebase with the current main branch. Thank you.

**Comment by adrianbenavides** [comment]
It's ready now @mrinalwadhwa

**Review by adrianbenavides — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
@adrianbenavides it would be better to maintain @NathanTarbert's signature. Would you mind doing a rebase with the current main branch with your signature. Thank you.

**Comment by mrinalwadhwa** [comment]
If you want to skip dealing with the merge commit. Another easy way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

**Comment by mrinalwadhwa** [comment]
Merged in https://github.com/build-trust/ockam-contributors/pull/168

**Pull request closed without merging**
