### PR TITLE
Updated the contributors file: added etorreborre

### PR DESCRIPTION
**Pull request by etorreborre**

### CODE REVIEW

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
Thank you for accepting the CLA!!

**Comment by etorreborre** [comment]
Thanks @mrinalwadhwa. Could you please have someone trigger the workflow for this very small PR: https://github.com/build-trust/ockam/pull/3880? It's a one word change, I hope I got it right :-).

**Comment by mrinalwadhwa** [comment]
triggered.

**Comment by symbiont-eric-torreborre** [comment]
Hi @mrinalwadhwa, sorry but I need a small push again on that PR (yes I managed to get it wrong because my development environment is not fully setup...). Thanks

**Comment by mrinalwadhwa** [comment]
no problem at all .. retriggered.

**Comment by etorreborre** [comment]
@mrinalwadhwa I'm going to need one more push, because of an additional issue with the commit message :-|. But this time I installed and ran `npx commitlint`. I will get there, I promise!

**Comment by etorreborre** [comment]
For my other projects I generally use [this tool](https://hackage.haskell.org/package/cmt) to avoid those issues.

**Pull request merged**
