### PR TITLE
Update CONTRIBUTORS.csv

### PR DESCRIPTION
**Pull request by justinmmott**

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@justinmmott Thank you for accepting the CLA!!
Before we merge, could you please rebase this PR to the latest main branch so your signature is maintained when we merge.

**Comment by justinmmott** [comment]
@mrinalwadhwa ok done

**Comment by mrinalwadhwa** [comment]
Thank you, looks like the commit is not signed / verified by github anymore.
Could you sign it please. 

Screen Shot 2022-10-21 at 3 41 41 PM

If you're not setup with GPG signing then the easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

**Review by mrinalwadhwa — APPROVED** [review]
Awesome, thank you. Looks great!

**Pull request merged**
