### PR TITLE
update contributors

### PR DESCRIPTION
**Pull request by davidag**
Accept CLA

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@davidag thank you for accepting the CLA!!

Would you mind rebasing this PR's branch to the main branch so your commit signature is maintained when I merge it. Thank you.

**Comment by davidag** [comment]
> @davidag thank you for accepting the CLA!!
> 
> Would you mind rebasing this PR's branch to the main branch so your commit signature is maintained when I merge it. Thank you.

@mrinalwadhwa Done! 👍🏼

**Comment by mrinalwadhwa** [comment]
@davidag Thank you. Looks like we're getting close to landing a couple of you PRs. Before we can ... your new commit in this PR isn't [Verified by Github](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification).

1. If you have signing key, please sign it.
2. If you don't have a signing key the easiest might me to 
Thank you for spending time on this, before we can merge please The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a new PR, this will make the commit as verified.

Also since the main branch has changed, it will need another rebase. Thank you.

Screen Shot 2022-11-03 at 8 25 20 AM

**Comment by davidag** [comment]
@mrinalwadhwa fixed!

**Review by mrinalwadhwa — APPROVED** [review]
Thank you for accepting the CLA!!

**Pull request merged**
