### PR TITLE
Added Contributor

### PR DESCRIPTION
**Pull request by m-ata**

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@m-ata thank you. Github shows your commit as Unverified. 

Screen Shot 2022-11-03 at 7 52 16 AM

Please add your public key yo github https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account

**Comment by m-ata** [comment]
@mrinalwadhwa I have added the GPG key in my account. Now, it shouldn't be `unverified`. Also, I have rebased my branch.

**Comment by mrinalwadhwa** [comment]
@m-ata the current commit isn't signed. Could you please check.

Screen Shot 2022-11-03 at 3 22 16 PM

**Comment by m-ata** [comment]
> @m-ata thank you. Github shows your commit as Unverified.
> 
> Screen Shot 2022-11-03 at 7 52 16 AM
> 
> Please add your public key yo github https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account

Screenshot 2022-11-03 at 23 30 51
I have added GPG Key to my account but it is still `unverified`. Do you have any idea why?

**Comment by mrinalwadhwa** [comment]
I suspect it might be because the email in your commit:

```
» git show
commit 58060690759761cac735dcb2c475d6f71bdcefd9 (HEAD -> feature/add-me-as-contributor)
Author: Muhammad Ata <Muhammad_ata@outlook.com>
Date:   Thu Nov 3 23:27:50 2022 +0100
```

is `<M...` but in your GPG public key as we see in your screenshot above is `<m...`
capital `M` vs. small `m`.

I think it would be fixed if you change your git config email to `<m...> ` and amend your commit to use that email. It will fix the problem.

**Comment by mrinalwadhwa** [comment]
@m-ata Thank you, it shows as Verified now. Could you do one final rebase please and I'll merge.


Screen Shot 2022-11-04 at 8 04 57 AM

**Comment by m-ata** [comment]
> @m-ata Thank you, it shows as Verified now. Could you do one final rebase please and I'll merge.
> 
> Screen Shot 2022-11-04 at 8 04 57 AM

@mrinalwadhwa  I rebased it. Please check and merge.

**Review by mrinalwadhwa — APPROVED** [review]
That looks great. Thank you!

**Pull request merged**
